# Generated by Django 2.2.6 on 2019-12-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['createdAt']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
